api:
  dashboard: true
  insecure: false  # Solo para entorno de desarrollo

entryPoints:
  web:
    address: ":80"
  dashboard:        # Añadir esta sección
    address: ":8090"

providers:
  # Permitir configuración dinámica mediante Consul
  consulCatalog:
    prefix: "traefik"
    exposedByDefault: false
    endpoint:
      address: "consul:8500"
      scheme: "http"
  # Permitir configuración estática mediante archivos
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Configuración por defecto para servicios
accessLog: {}
log:
  level: "INFO"