// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "title": "{{.Title}}",
        "description": "{{escape .Description}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users/me": {
            "get": {
                "tags": ["Users"],
                "summary": "Obtener información del usuario autenticado",
                "description": "Devuelve la información del usuario asociado al token de autenticación",
                "produces": ["application/json"],
                "security": [{"BearerAuth": []}],
                "responses": {
                    "200": { "description": "Usuario encontrado", "schema": {"$ref": "#/definitions/UserResponse"} },
                    "401": { "description": "No autorizado", "schema": {"$ref": "#/definitions/ErrorDTO"} },
                    "500": { "description": "Error interno", "schema": {"$ref": "#/definitions/ErrorDTO"} }
                }
            }
        },
        "/users/{id}": {
            "put": {
                "tags": ["Users"],
                "summary": "Actualizar usuario",
                "description": "Actualiza los datos del usuario identificado por el parámetro id",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"in": "body", "name": "user", "required": true, "schema": {"$ref": "#/definitions/UserRequest"}}
                ],
                "responses": {
                    "200": {"description": "Usuario actualizado", "schema": {"$ref": "#/definitions/UserResponse"}},
                    "400": {"description": "Entrada inválida", "schema": {"$ref": "#/definitions/ErrorDTO"}},
                    "401": {"description": "No autorizado", "schema": {"$ref": "#/definitions/ErrorDTO"}},
                    "404": {"description": "Usuario no encontrado", "schema": {"$ref": "#/definitions/ErrorDTO"}}
                }
            }
        },
        "/users/{id}/rol": {
            "patch": {
                "tags": ["Users"],
                "summary": "Actualizar rol de usuario",
                "description": "Actualiza el rol del usuario (solo administradores)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"name": "id", "in": "path", "required": true, "type": "string"},
                    {"in": "body", "name": "rol", "required": true, "schema": {"type": "object", "required": ["rol"], "properties": {"rol": {"type": "string", "description": "Rol a asignar. Valores permitidos: admin, producer, client"}}}}
                ],
                "responses": {
                    "200": {"description": "Rol actualizado", "schema": {"$ref": "#/definitions/UserResponse"}},
                    "400": {"description": "Entrada inválida", "schema": {"$ref": "#/definitions/ErrorDTO"}},
                    "401": {"description": "No autorizado", "schema": {"$ref": "#/definitions/ErrorDTO"}},
                    "404": {"description": "Usuario no encontrado", "schema": {"$ref": "#/definitions/ErrorDTO"}}
                }
            }
        }
    },
    "definitions": {
        "UserRequest": {
            "type": "object",
            "properties": {
                "firebaseUID": {"type": "string"},
                "email": {"type": "string", "format": "email"},
                "name": {"type": "string"},
                "rol": {"type": "string", "enum": ["admin", "producer", "client"]},
                "profile": {"$ref": "#/definitions/ProfileRequest"}
            },
            "required": ["email", "name"]
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "firebaseUID": {"type": "string"},
                "email": {"type": "string"},
                "name": {"type": "string"},
                "rol": {"type": "string", "enum": ["admin","producer","client"]},
                "profile": {"$ref": "#/definitions/ProfileResponse"}
            }
        },
        "ProfileRequest": {
            "type": "object",
            "properties": {
                "user_id": {"type": "string"},
                "address": {"type": "string"},
                "phone": {"type": "string"},
                "avatar_url": {"type": "string"}
            },
            "required": ["address","phone","avatar_url"]
        },
        "ProfileResponse": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "user_id": {"type": "string"},
                "address": {"type": "string"},
                "phone": {"type": "string"},
                "avatar_url": {"type": "string"},
                "created_at": {"type": "string", "format": "date-time"},
                "updated_at": {"type": "string", "format": "date-time"}
            }
        },
        "ErrorDTO": {
            "type": "object",
            "properties": {
                "timestamp": {"type": "string", "format": "date-time"},
                "status": {"type": "integer"},
                "error": {"type": "string"}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Usuarios",
	Description:      "Microservicio para la gestión de usuarios.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
